// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: admin.sql

package db

import (
	"context"
)

const createNewAdmin = `-- name: CreateNewAdmin :one
WITH new_admin AS (
INSERT INTO "Users" (username, email, hashedpassword, role)
VALUES ($1, $2, $3, 'Admin')
    RETURNING user_id
    )
INSERT INTO "Admins" (admin_id)
SELECT user_id
FROM new_admin RETURNING admin_id
`

type CreateNewAdminParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	Hashedpassword string `json:"hashedpassword"`
}

func (q *Queries) CreateNewAdmin(ctx context.Context, arg CreateNewAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createNewAdmin, arg.Username, arg.Email, arg.Hashedpassword)
	var admin_id int64
	err := row.Scan(&admin_id)
	return admin_id, err
}
