// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: issues.sql

package db

import (
	"context"
)

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE "Issues"
SET status = $2,
    comments = $3
WHERE issue_id = $1
RETURNING issue_id, description, status, comments, created_at
`

type UpdateIssueStatusParams struct {
	IssueID  int64  `json:"issue_id"`
	Status   string `json:"status"`
	Comments string `json:"comments"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssueStatus, arg.IssueID, arg.Status, arg.Comments)
	var i Issue
	err := row.Scan(
		&i.IssueID,
		&i.Description,
		&i.Status,
		&i.Comments,
		&i.CreatedAt,
	)
	return i, err
}
