// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddNewDrone(ctx context.Context, arg AddNewDroneParams) (Drone, error)
	CreateNewAdmin(ctx context.Context, arg CreateNewAdminParams) (int64, error)
	CreateNewCustomer(ctx context.Context, arg CreateNewCustomerParams) (Customer, error)
	CreateNewSecurityOfficer(ctx context.Context, arg CreateNewSecurityOfficerParams) (SecuritOfficer, error)
	DeleteDrone(ctx context.Context, droneID int64) (Drone, error)
	GetAlertsCountsByPriority(ctx context.Context, customerID int64) ([]GetAlertsCountsByPriorityRow, error)
	GetAllActiveSecurityOfficers(ctx context.Context, customerID int64) ([]User, error)
	GetAllAlerts(ctx context.Context, customerID int64) (SafetyDetectionAlert, error)
	GetAllDronesByCustomer(ctx context.Context, customerID int64) ([]Drone, error)
	GetAllIssuesByAllSecurityOfficers(ctx context.Context, customerID int64) ([]Issue, error)
	GetAllIssuesByCustomer(ctx context.Context, customerID int64) ([]Issue, error)
	GetAllOfficerIssues(ctx context.Context, arg GetAllOfficerIssuesParams) ([]Issue, error)
	GetAllUnResolvedAlertsByDetectionType(ctx context.Context, arg GetAllUnResolvedAlertsByDetectionTypeParams) ([]SafetyDetectionAlert, error)
	GetUnResolvedAlertsCountsByPriority(ctx context.Context, customerID int64) ([]GetUnResolvedAlertsCountsByPriorityRow, error)
	GetUser(ctx context.Context, userID int64) (User, error)
	StopDroneStream(ctx context.Context, arg StopDroneStreamParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
