// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, username, email, hashedpassword, role, created_at
FROM "Users"
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Hashedpassword,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
