// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addNewDrone": {
            "post": {
                "description": "adds a New Drone For Customer  in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "addNewDroneForCustomer",
                "parameters": [
                    {
                        "description": "adds a New Drone For Customer  in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AddNewDroneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/createAdmin": {
            "post": {
                "description": "adds a New admin in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "creates a new admin",
                "parameters": [
                    {
                        "description": "adds a New Drone For Customer  in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateNewAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/customer/getAllActiveOfficers": {
            "get": {
                "description": "returns all active security officers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "getActiveOfficers",
                "parameters": [
                    {
                        "description": "returns active security officers For Customer  in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetActiveOfficersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/customer/getAllDrones": {
            "get": {
                "description": "eturns all drones  of a Customer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "getAllDrones",
                "parameters": [
                    {
                        "description": "returns all drones  of a Customer  in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetAllDronesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/customer/getAllOfficerIssues": {
            "get": {
                "description": "returns all issues raised by officers  of a Customer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "getAllOfficerIssues",
                "parameters": [
                    {
                        "description": "returns all issues raised by officers  of a Customer in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetAllOfficerIssuesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/officer/createOfficer": {
            "post": {
                "description": "adds a New Security officer For Customer  in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "officer"
                ],
                "summary": "createNewSecurityOfficer",
                "parameters": [
                    {
                        "description": "adds a New officer For Customer  in Db",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateNewSecurityOfficerRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddNewDroneRequest": {
            "type": "object",
            "required": [
                "customer_id",
                "model",
                "status"
            ],
            "properties": {
                "customer_id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.CreateNewAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.CreateNewSecurityOfficerRequestRequest": {
            "type": "object",
            "required": [
                "customerid",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "customerid": {
                    "type": "integer"
                },
                "email": {
                    "type": "string",
                    "minLength": 6
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.GetActiveOfficersRequest": {
            "type": "object",
            "required": [
                "customerid"
            ],
            "properties": {
                "customerid": {
                    "type": "integer"
                }
            }
        },
        "api.GetAllDronesRequest": {
            "type": "object",
            "required": [
                "customerid"
            ],
            "properties": {
                "customerid": {
                    "type": "integer"
                }
            }
        },
        "api.GetAllOfficerIssuesRequest": {
            "type": "object",
            "required": [
                "customerid",
                "limit",
                "offset"
            ],
            "properties": {
                "customerid": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Drone Saefty Backend",
	Description:      "Drone Saefty Backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
