definitions:
  api.AddNewDroneRequest:
    properties:
      customer_id:
        type: integer
      model:
        type: string
      status:
        type: string
    required:
    - customer_id
    - model
    - status
    type: object
  api.CreateNewAdminRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  api.CreateNewSecurityOfficerRequestRequest:
    properties:
      customerid:
        type: integer
      email:
        minLength: 6
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - customerid
    - email
    - password
    - username
    type: object
  api.GetActiveOfficersRequest:
    properties:
      customerid:
        type: integer
    required:
    - customerid
    type: object
  api.GetAllDronesRequest:
    properties:
      customerid:
        type: integer
    required:
    - customerid
    type: object
  api.GetAllIssuesRequest:
    properties:
      customerid:
        type: integer
      limit:
        type: integer
      offset:
        type: integer
    required:
    - customerid
    - limit
    - offset
    type: object
host: 0.0.0.0:8080
info:
  contact: {}
  description: Drone Saefty Backend
  title: Drone Saefty Backend
  version: "1.0"
paths:
  /addNewDrone:
    post:
      description: adds a New Drone For Customer  in Db.
      parameters:
      - description: adds a New Drone For Customer  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.AddNewDroneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: addNewDroneForCustomer
      tags:
      - customer
  /admin/createAdmin:
    post:
      description: adds a New admin in Db.
      parameters:
      - description: adds a New Drone For Customer  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.CreateNewAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: creates a new admin
      tags:
      - admin
  /customer/getAllActiveOfficers:
    get:
      description: returns all active security officers.
      parameters:
      - description: returns active security officers For Customer  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.GetActiveOfficersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getActiveOfficers
      tags:
      - customer
  /customer/getAllDrones:
    get:
      description: eturns all drones  of a Customer.
      parameters:
      - description: returns all drones  of a Customer  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.GetAllDronesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getAllDrones
      tags:
      - customer
  /customer/getAllIssuesByCustomer:
    get:
      description: returns all issues raised by Customer.
      parameters:
      - description: returns all issues raised by customers  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.GetAllIssuesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getAllIssuesByCustomer
      tags:
      - customer
  /customer/getAllOfficerIssues:
    get:
      description: returns all issues raised by officers  of a Customer.
      parameters:
      - description: returns all issues raised by officers  of a Customer in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.GetAllIssuesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getAllOfficerIssues
      tags:
      - customer
  /officer/createOfficer:
    post:
      description: adds a New Security officer For Customer  in Db.
      parameters:
      - description: adds a New officer For Customer  in Db
        in: body
        name: device
        required: true
        schema:
          $ref: '#/definitions/api.CreateNewSecurityOfficerRequestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: createNewSecurityOfficer
      tags:
      - officer
swagger: "2.0"
